$('.drag').draggable({ 
    appendTo: 'body',
    helper: 'clone'
    });

    $('#dropzone').droppable({
    activeClass: 'active',
    hoverClass: 'hover',
    accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
    drop: function (e, ui) {
        if (ui.draggable[0].id == 'textbox') {
           var $el = $('<div class="form-group drop-item"><label id="lbl">Label</label><input type="text" name="' + ui.draggable.text() + '" class="form-control" value=""></div>');
        } else if (ui.draggable[0].id == 'textarea') {
          var $el = $('<div class="form-group drop-item"<label id="lbl">Label</label><textarea class="form-control" name="' + ui.draggable.text() + '" rows="3"></textarea>');
        } else if (ui.draggable[0].id == 'select') {
          var $el = $('<div class="form-group drop-item"><details><summary><label id="lbl">Label</label><select class="form-control"><option>Selecione</select></summary><div><label>More Data</label><input type="text" /></div></details></div>');
        } else if (ui.draggable[0].id == 'button') {
          var $el = $('<div class="form-group drop-item"><details><summary>  <button type="submit" class="btn btn-primary mb-2">Enviar</button></summary><div><label>More Data</label><input type="text" /></div></details></div>');
        } else {
          var $el = $('<div class="drop-item"><details><summary>' + ui.draggable.text() + '</summary><div><label>More Data</label><input type="text" /></div></details></div>');
        }  
        $el.append($('<div><button type="button" class="btn btn-default btn-xs remove"><span class="glyphicon glyphicon-trash"></span></button></div>').click(function () { $(this).parent().detach(); }));

        if (ui.draggable[0].id == 'textbox') {
          $el.append($('<div><button type="button" class="btn btn-default btn-xs"><i class="fa-solid fa-screwdriver-wrench"></span></button></div>').click(function () { $("#properties").html('<div class="form-group"><label>ID</label><input name="id" class="form-control" type="text" value="" /></div><div class="form-group"><label>Name</label><input name="name" class="form-control" type="text" value="" /></div>').resize(); }));
        } else if (ui.draggable[0].id == 'textarea') {
          $el.append($('<div><button type="button" class="btn btn-default btn-xs"><i class="fa-solid fa-screwdriver-wrench"></span></button></div>').click(function () { $("#properties").html('<div class="form-group"><label>ID</label><input name="id" class="form-control" type="text" value="" /></div><div class="form-group"><label>Name</label><input name="name" class="form-control" type="text" value="" /></div><div class="form-group"><label>Rows</label><input name="rows" class="form-control" type="text" value="3" /></div>').resize(); }));
        }
        $(this).append($el);
    }
    }).sortable({
    items: '.drop-item',
    sort: function() {
        // gets added unintentionally by droppable interacting with sortable
        // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
        $( this ).removeClass( "active" );
    }
    });